<?php

declare(strict_types=1);

namespace App\Command;

use App\BookBlueprint\CoverGenerationService;
use App\Integration\Replicate\ReplicatePredictionClientInterface;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(
    name: 'app:book:generate-cover',
    description: 'Generates a single cover image locally from a Master Blueprint V2 using Replicate FLUX 2 Pro.',
)]
final class GenerateCoverCommand extends Command
{
    private const REQUIRED_MODEL = 'black-forest-labs/flux-2-pro';
    private const POLL_TIMEOUT_SECONDS = 180;
    private const POLL_SLEEP_MICROSECONDS = 1500000;
    private const MAX_GENERATION_ATTEMPTS = 3;
    private const RETRY_SLEEP_MICROSECONDS = 1000000;

    public function __construct(
        private readonly CoverGenerationService $coverGenerationService,
        private readonly ReplicatePredictionClientInterface $replicatePredictionClient,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->addOption('source', null, InputOption::VALUE_REQUIRED, 'Path to the master blueprint JSON file.')
            ->addOption('photo', null, InputOption::VALUE_REQUIRED, 'Optional child photo path.')
            ->addOption('hero-reference', null, InputOption::VALUE_REQUIRED, 'Optional path to hero-reference.png generated by page_1 (locks hero identity on cover).')
            ->addOption('output-dir', null, InputOption::VALUE_REQUIRED, 'Optional output directory.')
            ->addOption('force', null, InputOption::VALUE_NONE, 'Regenerate the cover even if cover-generated.png already exists.')
            ->addOption('dry-run', null, InputOption::VALUE_NONE, 'Build the cover prompt and debug payload without calling Replicate.');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $sourcePath = trim((string) $input->getOption('source'));
        $photoPath = trim((string) $input->getOption('photo'));
        $heroReferencePath = trim((string) $input->getOption('hero-reference'));
        $force = (bool) $input->getOption('force');
        $dryRun = (bool) $input->getOption('dry-run');

        if ('' === $sourcePath || !is_file($sourcePath) || !is_readable($sourcePath)) {
            $io->error('The --source option is required and must point to a readable master blueprint JSON file.');

            return Command::FAILURE;
        }

        $outputDir = rtrim(trim((string) $input->getOption('output-dir')), '/');
        if ('' === $outputDir || $outputDir === dirname($sourcePath)) {
            $outputDir = dirname($sourcePath).'/generated-cover';
        }

        try {
            $masterBlueprint = json_decode((string) file_get_contents($sourcePath), true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $exception) {
            $io->error(sprintf('Invalid JSON: %s', $exception->getMessage()));

            return Command::FAILURE;
        }

        if (!is_array($masterBlueprint)) {
            $io->error('The master blueprint root must be a JSON object.');

            return Command::FAILURE;
        }

        try {
            $coverScene = $this->coverGenerationService->validateAndExtractCover($masterBlueprint);
            $payload = $this->coverGenerationService->buildCoverGenerationPayload(
                $masterBlueprint,
                $coverScene,
                '' !== $photoPath ? $photoPath : null,
                '' !== $heroReferencePath ? $heroReferencePath : null,
            );
        } catch (\RuntimeException $exception) {
            $io->error($exception->getMessage());

            return Command::FAILURE;
        }

        $io->section('Cover Generation Report');
        $io->writeln(sprintf('Source: %s', $sourcePath));
        $io->writeln(sprintf('Output directory: %s', $outputDir));
        $io->writeln(sprintf('Dry run: %s', $dryRun ? 'yes' : 'no'));
        $io->writeln(sprintf('Force: %s', $force ? 'yes' : 'no'));
        $io->writeln(sprintf('Photo provided:       %s', '' !== $photoPath ? 'yes' : 'no'));
        $io->writeln(sprintf('Hero reference:       %s', '' !== $heroReferencePath ? $heroReferencePath : 'none'));
        $io->writeln(sprintf('Model: %s', self::REQUIRED_MODEL));
        $io->writeln(sprintf('Scene: %s', (string) ($coverScene['id'] ?? 'cover')));

        if ((!file_exists($outputDir) && !@mkdir($outputDir, 0775, true) && !is_dir($outputDir)) || (file_exists($outputDir) && !is_dir($outputDir))) {
            $io->error(sprintf('The output directory "%s" is not writable.', $outputDir));

            return Command::FAILURE;
        }

        $coverOutputPath = $outputDir.'/cover-generated.png';

        if (!$dryRun && !$force && is_file($coverOutputPath)) {
            $this->writeDebugArtifacts(
                $sourcePath,
                $outputDir,
                '' !== $photoPath ? $photoPath : null,
                (string) ($coverScene['id'] ?? 'cover'),
                $payload['prompt'],
                $payload['negativePrompt'],
                $payload['input'],
                false,
                [
                    'status' => 'skipped',
                    'reason' => 'existing_output',
                    'output' => [$coverOutputPath],
                ],
            );
            $io->success('Cover already exists. Reused existing cover-generated.png; use --force to regenerate.');

            return Command::SUCCESS;
        }

        if ($dryRun) {
            $this->writeDebugArtifacts(
                $sourcePath,
                $outputDir,
                '' !== $photoPath ? $photoPath : null,
                (string) ($coverScene['id'] ?? 'cover'),
                $payload['prompt'],
                $payload['negativePrompt'],
                $payload['input'],
                true,
                null,
            );
            $io->writeln(sprintf('Prompt preview: %s', $payload['prompt']));
            $io->success('Cover prompt built successfully in dry-run mode.');

            return Command::SUCCESS;
        }

        $this->replicatePredictionClient->assertConfigured();

        if ($this->replicatePredictionClient->getModelReference() !== self::REQUIRED_MODEL) {
            $io->error(sprintf(
                'REPLICATE_MODEL must be set to "%s" for this command. Current value: "%s".',
                self::REQUIRED_MODEL,
                $this->replicatePredictionClient->getModelReference(),
            ));

            return Command::FAILURE;
        }

        try {
            $this->writeDebugArtifacts(
                $sourcePath,
                $outputDir,
                '' !== $photoPath ? $photoPath : null,
                (string) ($coverScene['id'] ?? 'cover'),
                $payload['prompt'],
                $payload['negativePrompt'],
                $payload['input'],
                false,
                [
                    'status' => 'prepared',
                    'prediction' => null,
                ],
            );
            $finalPrediction = $this->runPredictionWithRetry($payload['input']);
            $outputUrls = $this->extractOutputUrls($finalPrediction['output'] ?? null);

            if ([] === $outputUrls) {
                throw new \RuntimeException('Replicate completed without an output image URL.');
            }

            $downloaded = $this->replicatePredictionClient->downloadFile($outputUrls[0]);
            if (false === file_put_contents($coverOutputPath, $downloaded['content']) || !is_file($coverOutputPath)) {
                throw new \RuntimeException(sprintf('The generated cover could not be written to "%s".', $coverOutputPath));
            }
            $this->writeDebugArtifacts(
                $sourcePath,
                $outputDir,
                '' !== $photoPath ? $photoPath : null,
                (string) ($coverScene['id'] ?? 'cover'),
                $payload['prompt'],
                $payload['negativePrompt'],
                $payload['input'],
                false,
                $finalPrediction,
            );
        } catch (\RuntimeException $exception) {
            $io->error($exception->getMessage());

            return Command::FAILURE;
        }

        $io->success('Cover generated successfully.');
        $io->writeln('Files written: cover-generated.png, cover-prompt.txt, cover-negative-prompt.txt, cover-debug.json');

        return Command::SUCCESS;
    }

    /** @return array<string, mixed> */
    private function waitForPrediction(string $predictionId): array
    {
        if ('' === trim($predictionId)) {
            throw new \RuntimeException('Replicate did not return a prediction id.');
        }

        $startedAt = time();

        do {
            $prediction = $this->replicatePredictionClient->getPrediction($predictionId);
            $status = trim((string) ($prediction['status'] ?? 'processing'));

            if (in_array($status, ['succeeded', 'failed', 'canceled'], true)) {
                if ('succeeded' !== $status) {
                    throw new \RuntimeException(sprintf('Replicate cover generation ended with status "%s": %s', $status, trim((string) ($prediction['error'] ?? 'unknown error'))));
                }

                return $prediction;
            }

            usleep(self::POLL_SLEEP_MICROSECONDS);
        } while ((time() - $startedAt) < self::POLL_TIMEOUT_SECONDS);

        throw new \RuntimeException(sprintf('Replicate cover generation timed out after %d seconds.', self::POLL_TIMEOUT_SECONDS));
    }

    /** @param array<string, mixed> $input @return array<string, mixed> */
    private function runPredictionWithRetry(array $input): array
    {
        $lastException = null;

        for ($attempt = 1; $attempt <= self::MAX_GENERATION_ATTEMPTS; ++$attempt) {
            try {
                $prediction = $this->replicatePredictionClient->createPrediction($input);

                return $this->waitForPrediction((string) ($prediction['id'] ?? ''));
            } catch (\RuntimeException $exception) {
                $lastException = $exception;
                if ($attempt >= self::MAX_GENERATION_ATTEMPTS || !$this->isTransientReplicateFailure($exception)) {
                    throw $exception;
                }

                usleep(self::RETRY_SLEEP_MICROSECONDS);
            }
        }

        throw $lastException ?? new \RuntimeException('Cover generation failed unexpectedly.');
    }

    /** @return list<string> */
    private function extractOutputUrls(mixed $output): array
    {
        if (is_string($output) && '' !== trim($output)) {
            return [trim($output)];
        }

        if (!is_array($output)) {
            return [];
        }

        $urls = [];
        foreach ($output as $value) {
            if (is_string($value) && '' !== trim($value)) {
                $urls[] = trim($value);
            }
        }

        return $urls;
    }

    /**
     * @param array<string, mixed> $replicateInputPayload
     * @param array<string, mixed>|null $prediction
     */
    private function writeDebugArtifacts(
        string $sourcePath,
        string $outputDir,
        ?string $photoPath,
        string $scene,
        string $prompt,
        string $negativePrompt,
        array $replicateInputPayload,
        bool $dryRun,
        ?array $prediction,
    ): void {
        file_put_contents($outputDir.'/cover-prompt.txt', $prompt."\n");
        file_put_contents($outputDir.'/cover-negative-prompt.txt', $negativePrompt."\n");
        file_put_contents($outputDir.'/cover-debug.json', json_encode([
            'source' => $sourcePath,
            'model' => self::REQUIRED_MODEL,
            'scene' => $scene,
            'dryRun' => $dryRun,
            'photoProvided' => null !== $photoPath,
            'outputDir' => $outputDir,
            'prompt' => $prompt,
            'negativePrompt' => $negativePrompt,
            'replicateInputPayload' => $replicateInputPayload,
            'prediction' => $prediction,
            'estimatedCostUsd' => 0.055,
        ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)."\n");
    }

    private function isTransientReplicateFailure(\RuntimeException $exception): bool
    {
        $message = strtolower($exception->getMessage());

        return str_contains($message, 'prediction interrupted')
            || str_contains($message, '(code: pa)')
            || str_contains($message, 'async prediction failed')
            || str_contains($message, 'readerror')
            || str_contains($message, 'error generating image');
    }
}
