<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260428120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Store PDF artifacts privately with controlled access tokens and persist fulfillment webhook idempotency events.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE app_personalization_pdf_artifact ADD access_token VARCHAR(64) DEFAULT NULL');
        $this->addSql("UPDATE app_personalization_pdf_artifact SET access_token = md5(CAST(id AS TEXT) || COALESCE(public_path, '')) WHERE access_token IS NULL");
        $this->addSql('ALTER TABLE app_personalization_pdf_artifact ALTER access_token SET NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_743D6C047015309 ON app_personalization_pdf_artifact (access_token)');
        $this->addSql('CREATE TABLE app_fulfillment_webhook_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_key VARCHAR(128) NOT NULL, provider_name VARCHAR(32) NOT NULL, payload JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_fulfillment_webhook_event_key ON app_fulfillment_webhook_event (event_key)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE app_fulfillment_webhook_event');
        $this->addSql('DROP INDEX UNIQ_743D6C047015309');
        $this->addSql('ALTER TABLE app_personalization_pdf_artifact DROP access_token');
    }
}
