services:
    App\Tests\Double\Stripe\FakeStripeCheckoutClient:
        public: true

    App\Stripe\StripeCheckoutClientInterface: '@App\Tests\Double\Stripe\FakeStripeCheckoutClient'

    App\Tests\Double\Gelato\FakeGelatoClient:
        public: true

    App\Gelato\GelatoClientInterface: '@App\Tests\Double\Gelato\FakeGelatoClient'
