#!/usr/bin/env bash
# ============================================================
# Railway production deployment script
#
# Usage:
#   RAILWAY_TOKEN=<your-token> bash scripts/railway-deploy.sh
#
# Obtain your token at: https://railway.com/account/tokens
# ============================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [ -z "${RAILWAY_TOKEN:-}" ]; then
    echo "ERROR: RAILWAY_TOKEN is not set."
    echo "  1. Go to https://railway.com/account/tokens"
    echo "  2. Create a token"
    echo "  3. Run: RAILWAY_TOKEN=<token> bash scripts/railway-deploy.sh"
    exit 1
fi

export RAILWAY_TOKEN

echo "=== [1/7] Authenticating with Railway ==="
railway whoami

echo ""
echo "=== [2/7] Creating Railway project ==="
echo "    Run this manually if the project already exists:"
echo "    RAILWAY_TOKEN=<token> railway init"
echo ""
echo "    Then link the existing project with:"
echo "    RAILWAY_TOKEN=<token> railway link <project-id>"
echo ""
echo "    Press ENTER to continue (project must already exist and be linked)"
read -r

echo ""
echo "=== [3/7] Checking current project status ==="
railway status

echo ""
echo "=== [4/7] Setting production environment variables ==="
echo "    IMPORTANT: Provide the following values when prompted."
echo ""

# Core
railway vars set APP_ENV=prod
railway vars set APP_DEBUG=0
railway vars set APP_RUNTIME_MODE=web=1
railway vars set APP_SHARE_DIR=var/share
railway vars set PHP_DATE_TIMEZONE=Europe/Brussels
railway vars set DEFAULT_URI=https://$(railway domain 2>/dev/null | grep -o '[a-z0-9.-]*railway.app' | head -1 || echo "YOUR_RAILWAY_DOMAIN.railway.app")

# Messenger (Doctrine transport — no external queue needed)
railway vars set MESSENGER_TRANSPORT_DSN=doctrine://default
railway vars set SYLIUS_MESSENGER_TRANSPORT_MAIN_DSN=doctrine://default
railway vars set SYLIUS_MESSENGER_TRANSPORT_MAIN_FAILED_DSN="doctrine://default?queue_name=main_failed"
railway vars set SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_DSN="doctrine://default?queue_name=catalog_promotion_removal"
railway vars set SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_FAILED_DSN="doctrine://default?queue_name=catalog_promotion_removal_failed"
railway vars set SYLIUS_MESSENGER_TRANSPORT_PAYMENT_REQUEST_DSN=sync://
railway vars set SYLIUS_MESSENGER_TRANSPORT_PAYMENT_REQUEST_FAILED_DSN=sync://

# Payment encryption key (reads from config/encryption/test.key baked into image)
railway vars set SYLIUS_PAYMENT_ENCRYPTION_KEY_PATH=/srv/sylius/config/encryption/test.key

# JWT keys (generated by entrypoint.sh at first boot — passphrase must match)
railway vars set JWT_SECRET_KEY=/srv/sylius/config/jwt/private.pem
railway vars set JWT_PUBLIC_KEY=/srv/sylius/config/jwt/public.pem

# CORS (frontend domain — must match your Vercel production URL)
railway vars set CORS_ALLOW_ORIGIN="^https://(www\.)?monlivremagique\.be$"

# Frontend base URL (for Stripe redirect after payment)
railway vars set FRONTEND_BASE_URL=https://www.monlivremagique.be

echo ""
echo "=== [5/7] Secrets to set manually ==="
echo ""
echo "    Run each of these with your actual values:"
echo ""
echo "    railway vars set APP_SECRET=<generate: openssl rand -hex 32>"
echo "    railway vars set JWT_PASSPHRASE=<generate: openssl rand -hex 32>"
echo ""
echo "    # Replicate AI generation"
echo "    railway vars set REPLICATE_API_BASE_URI=https://api.replicate.com/v1"
echo "    railway vars set REPLICATE_MODEL=black-forest-labs/flux-2-pro"
echo "    railway vars set REPLICATE_MAX_RETRIES=2"
echo "    railway vars set PERSONALIZATION_GENERATION_PAGE_LIMIT=4"
echo "    railway vars set REPLICATE_API_TOKEN=r8_..."
echo ""
echo "    # Stripe PRODUCTION keys (not test keys!)"
echo "    railway vars set STRIPE_SECRET_KEY=sk_live_..."
echo "    railway vars set STRIPE_WEBHOOK_SECRET=whsec_..."
echo ""
echo "    # Gelato"
echo "    railway vars set GELATO_API_BASE_URI=https://order.gelatoapis.com"
echo "    railway vars set GELATO_PRODUCT_UID=photobooks-hardcover_pf_200x200-mm-8x8-inch_pt_170-gsm-65lb-coated-silk_cl_4-4_ccl_4-4_bt_glued-left_ct_matt-lamination_prt_1-0_cpt_130-gsm-65-lb-cover-coated-silk_ver"
echo "    railway vars set GELATO_SHIPMENT_METHOD_UID=standard"
echo "    railway vars set GELATO_API_KEY=..."
echo "    railway vars set GELATO_WEBHOOK_SECRET=<generate: openssl rand -hex 32>"
echo ""
echo "    # Support operations"
echo "    railway vars set SUPPORT_OPERATIONS_TOKEN=<generate: openssl rand -hex 32>"
echo ""
echo "    # Mailer (use a real SMTP in production)"
echo "    railway vars set MAILER_DSN=smtp://user:pass@smtp.example.com:587"
echo ""
echo "    # Alerts (optional)"
echo "    railway vars set ALERT_EMAIL_TO=ops@monlivremagique.be"
echo "    railway vars set ALERT_WEBHOOK_URL=https://hooks.slack.com/..."
echo ""
echo "    After setting all secrets, press ENTER to deploy."
read -r

echo ""
echo "=== [6/7] Deploying to Railway ==="
railway up --detach

echo ""
echo "=== [7/7] Post-deploy: verify catalog bootstrap ==="
echo ""
echo "    On a first deploy with an empty DB, entrypoint.sh now does this automatically:"
echo ""
echo "    1. app:sync-catalog"
echo ""
echo "    If you need to replay it manually on an existing environment:"
echo ""
echo "    railway run php bin/console app:sync-catalog --no-interaction"
echo "    railway run php bin/console app:diagnose-catalog-locales --no-interaction"
echo ""
echo "    Then configure:"
echo ""
RAILWAY_URL=$(railway domain 2>/dev/null | grep -o '[a-z0-9.-]*railway.app' | head -1 || echo "YOUR_RAILWAY_DOMAIN.railway.app")
echo "    1. Update frontend/vercel.json — replace RAILWAY_BACKEND_URL with: ${RAILWAY_URL}"
echo "    2. Push vercel.json → redeploy Vercel"
echo "    3. Add Stripe webhook: https://${RAILWAY_URL}/api/custom/payments/stripe/webhook"
echo "    4. Add Gelato webhook: https://${RAILWAY_URL}/api/custom/fulfillment/gelato/webhook?secret=<GELATO_WEBHOOK_SECRET>"
echo "    5. Change admin password: railway run php bin/console sylius:admin:change-password admin@example.com <new-password>"
echo ""
echo "=== Done ==="
