<?php

declare(strict_types=1);

namespace App\BookBlueprint;

final class CoverGenerationService
{
    public function __construct(
        private readonly BlueprintValidator $blueprintValidator,
        private readonly CoverPromptBuilder $coverPromptBuilder,
    ) {
    }

    /**
     * @param array<string, mixed> $masterBlueprint
     * @return array<string, mixed>
     */
    public function validateAndExtractCover(array $masterBlueprint): array
    {
        $validation = $this->blueprintValidator->validateMasterBlueprint($masterBlueprint);

        if (!$validation->isValid()) {
            throw new \RuntimeException(implode("\n", $validation->errors));
        }

        $coverScene = $this->findCoverScene($masterBlueprint);

        if (null === $coverScene) {
            throw new \RuntimeException('The master blueprint is missing its cover sceneDefinition.');
        }

        return $coverScene;
    }

    /**
     * @param array<string, mixed> $masterBlueprint
     * @param array<string, mixed> $coverScene
     * @param string|null $heroReferencePath path to hero-reference.png generated by page_1
     * @return array{prompt:string,negativePrompt:string,input:array<string,mixed>,debug:array<string,mixed>}
     */
    public function buildCoverGenerationPayload(array $masterBlueprint, array $coverScene, ?string $photoPath = null, ?string $heroReferencePath = null): array
    {
        $builtPrompt = $this->coverPromptBuilder->build(
            $masterBlueprint,
            $coverScene,
            null !== $photoPath,
            null !== $heroReferencePath,
        );
        $imageGeneration = is_array($masterBlueprint['imageGeneration'] ?? null) ? $masterBlueprint['imageGeneration'] : [];
        $input = [
            'prompt' => $builtPrompt['prompt'],
            'aspect_ratio' => trim((string) ($coverScene['aspectRatio'] ?? '3:4')) ?: '3:4',
            'resolution' => trim((string) ($imageGeneration['resolution'] ?? '1 MP')) ?: '1 MP',
            'output_format' => trim((string) ($imageGeneration['outputFormat'] ?? 'png')) ?: 'png',
        ];

        if ('' !== $builtPrompt['negativePrompt']) {
            $input['negative_prompt'] = $builtPrompt['negativePrompt'];
        }

        // Build input_images: hero reference takes precedence over child photo when both present
        $inputImages = [];
        if (null !== $heroReferencePath) {
            $inputImages[] = $this->toDataUri($heroReferencePath);
        }

        if (null !== $photoPath) {
            $inputImages[] = $this->toDataUri($photoPath);
        }

        if ([] !== $inputImages) {
            $input['input_images'] = $inputImages;
        }

        return [
            'prompt' => $builtPrompt['prompt'],
            'negativePrompt' => $builtPrompt['negativePrompt'],
            'input' => $input,
            'debug' => [
                'sceneId' => (string) ($coverScene['id'] ?? 'cover'),
                'sceneType' => (string) ($coverScene['type'] ?? 'cover'),
                'photoProvided' => null !== $photoPath,
                'heroReferenceProvided' => null !== $heroReferencePath,
                'promptBreakdown' => $builtPrompt['debug'],
            ],
        ];
    }

    /** @param array<string, mixed> $masterBlueprint @return array<string, mixed>|null */
    private function findCoverScene(array $masterBlueprint): ?array
    {
        $sceneDefinitions = is_array($masterBlueprint['sceneDefinitions'] ?? null) ? $masterBlueprint['sceneDefinitions'] : [];

        foreach ($sceneDefinitions as $scene) {
            if (is_array($scene) && ($scene['id'] ?? null) === 'cover') {
                return $scene;
            }
        }

        return null;
    }

    private function toDataUri(string $photoPath): string
    {
        if (!is_file($photoPath) || !is_readable($photoPath)) {
            throw new \RuntimeException(sprintf('Photo file "%s" is not readable.', $photoPath));
        }

        $contents = (string) file_get_contents($photoPath);
        $mimeType = mime_content_type($photoPath) ?: 'application/octet-stream';

        return sprintf('data:%s;base64,%s', $mimeType, base64_encode($contents));
    }
}
