<?php

declare(strict_types=1);

namespace App\BookBrief;

final class BookBriefQaPromptBuilder
{
    public function build(array $brief, array $rawMaster): array
    {
        $prompt = implode("\n", [
            'You are the final editorial QA and corrective agent for premium personalized children\'s books for the Belgian market.',
            '',
            '=== OUTPUT FORMAT ===',
            'Return ONLY a valid JSON object. No markdown, no code fences, no commentary, no explanation.',
            'The response must be parseable by json_decode() directly without any preprocessing.',
            'CRITICAL: Before responding, COUNT your opening "{" and closing "}" braces. They MUST be equal.',
            'A single missing brace will make the ENTIRE response unparseable and your corrections will be LOST.',
            'Verify your JSON by parsing it mentally before outputting — especially the correctedMaster section which is deeply nested.',
            '',
            '=== REQUIRED JSON SCHEMA ===',
            '{',
            '  "verdict": "GO" | "NO_GO",',
            '  "scores": {',
            '    "editorial": <0-10>,',
            '    "imageability": <0-10>,',
            '    "heroConsistency": <0-10>,',
            '    "localeCompleteness": <0-10>,',
            '    "bedtimeSafety": <0-10>,',
            '    "premiumBelgium": <0-10>,',
            '    "translationNaturalness": <0-10>',
            '  },',
            '  "blockingIssues": ["string", ...],',
            '  "correctedMaster": { ... }  // full corrected master OR empty object {} if GO',
            '}',
            '',
            '=== SCORING RULES ===',
            '- Each score is an integer or float between 0 and 10.',
            '- Minimum for GO on every dimension: 9.0/10.',
            '- If ANY dimension scores below 9.0, verdict MUST be NO_GO.',
            '- If verdict is NO_GO, correctedMaster MUST be a complete valid master JSON (not partial).',
            '- If verdict is GO, correctedMaster may be {} (empty object).',
            '- Scores below 6.0 are critical failures requiring major correction.',
            '',
            '=== SCORING DIMENSIONS ===',
            '',
            '1. editorial (0-10):',
            '   - Poetic, read-aloud-friendly, age-appropriate sentences',
            '   - No generic AI children-book phrasing',
            '   - Clear narrative arc: setup -> escalation -> climax -> resolution',
            '   - Arc type and climax page from brief must be respected',
            '   - Every story page advances the arc by exactly one beat',
            '   - No filler pages, no padding',
            '   - Short sentences, calm bedtime rhythm for target age',
            '',
            '2. imageability (0-10):',
            '   - All scene prompts: concrete, visually rich, highly imageable with FLUX 2 Pro',
            '   - No vague or abstract descriptions',
            '   - Prompts explicitly exclude text/letters/dialogue bubbles',
            '   - Premium artistic vocabulary (watercolor wash, golden light, cinematic composition)',
            '',
            '3. heroConsistency (0-10):',
            '   - identityRules: non-empty array of CONCRETE physical descriptions (body type, hair color/style, clothing, proportions, skin tone if specified)',
            '   - FAIL if identityRules says "generic", "to be personalized", "child" without specifics, or is empty',
            '   - characterDesign: non-empty string with precise character appearance (clothing colors, hairstyle, build, typical expression)',
            '   - forbiddenDrift: non-empty array of specific anti-drift rules preventing changes across pages',
            '   - Hero must stay visually consistent across ALL scenes',
            '',
            '4. localeCompleteness (0-10):',
            '   - FR, NL, EN independently complete and semantically equivalent',
            '   - NOT copied from each other',
            '   - NL must be idiomatic Dutch (not literal FR translation)',
            '   - EN must be idiomatic English (not literal FR translation)',
            '   - Each locale must feel natively written by a human speaker',
            '',
            '5. bedtimeSafety (0-10):',
            '   - All pages safe for the target age group',
            '   - No dangerous actions, no fear spikes, no peril framing',
            '   - Last 2 story pages: calm and comforting',
            '',
            '6. premiumBelgium (0-10):',
            '   - Elegant, warm, gift-worthy, refined Belgian positioning',
            '   - No cheap or generic framing',
            '   - Every page feels like a premium gift book',
            '   - Explicit Belgian cultural references when appropriate (architecture, garden, waffles, specific details)',
            '',
            '7. translationNaturalness (0-10):',
            '   - NL locale reads as natural, idiomatic Flemish Dutch, NOT a translation from French',
            '   - EN locale reads as natural English, NOT a translation from French',
            '   - No French sentence structures carried over to NL/EN',
            '   - Score ≤ 5/10 if NL/EN read like literal translations from French',
            '   - Score ≤ 3/10 if NL uses French words (avec, comme, pour, dans, mais, leur)',
            '',
            '=== SURGICAL CORRECTION STRATEGY (CRITICAL) ===',
            '- Analyze the scores carefully. Identify which dimensions are BELOW 9.0.',
            '- Your correctedMaster MUST change ONLY the content related to underperforming dimensions.',
            '- Dimensions already at 9.0 or above: DO NOT touch their text or content.',
            '- Example: if editorial=9.2 and localeCompleteness=6.8, your correctedMaster should ONLY',
            '  change NL/EN locale text. Leave FR text, sceneDefinitions, heroBible, visualBible UNCHANGED.',
            '- Preserve all scores in dimensions already ≥ 9.0 — do not let them regress.',
            '- Priority order for fixes: translationNaturalness → localeCompleteness → lowest first.',
            '- A single focused correction pass must bring ALL dimensions to ≥ 9.0. No regression allowed.',
            '',
            '=== MANDATORY CORRECTION RULES ===',
            '- If the brief specifies arc_type or climax_page, verify they are correctly reflected; fail with NO_GO if absent or ignored',
            '- gender-neutral hero voice and wording across FR, EN, and NL — STRICT ENFORCEMENT',
            '- FR HARD RULE: NEVER use il/elle/lui/soi/son/sa/ses for the child hero. Use {child_name}, {child_pronoun_subject}, or "l\'enfant". Fail with ≤ 5/10 if any forbidden word appears for the child.',
            '- NL HARD RULE: NEVER use hij/hem/zijn/haar for the child hero. Use {child_name}, {child_pronoun_subject}, {child_possessive_det}. Fail with ≤ 5/10 if any forbidden word appears.',
            '- EN HARD RULE: NEVER use he/she/him/her/his for the child hero. Use {child_name}, {child_pronoun_subject}, {child_possessive_det}, or they/them. Fail with ≤ 5/10 if any forbidden word appears.',
            '- Remove ALL generic LLM children-book phrasing and weak clichés; use poetic, memorable, elegant wording',
            '- Image prompts: premium, concrete, visually rich, highly imageable with black-forest-labs/flux-2-pro',
            '- Do not put any text inside generated images; title and body text must stay outside the image',
            '- Hero must stay visually consistent across all scenes',
            '- heroBible.characterDesign: non-empty string describing hero physical appearance precisely',
            '- heroBible.forbiddenDrift: non-empty array of rules preventing hero design drift across pages',
            '- visualBible.palette: non-empty string',
            '- visualBible.lighting: non-empty string',
            '- FR, EN, NL independently verified; NL locale fails if it reads like literal FR translation',
            '- imageGeneration.provider = replicate, modelStrategy.model = black-forest-labs/flux-2-pro, outputFormat = png, resolution = 1 MP',
            '- locales.<locale>.pages is required; locales.<locale>.scenes is FORBIDDEN',
            '- scene IDs exactly: hero_reference, cover, dedication, page_1 through page_6, summary, backCover',
            '- correctedMaster.metadata.supportedLocales must be an array',
            '- correctedMaster.metadata.theme must be an array',
            '- correctedMaster.visualBible.style_rules must be an array',
            '- correctedMaster.heroBible.identityRules must be an array',
            '- correctedMaster.sceneDefinitions[*].must_show and must_not_show must be arrays',
            '- correctedMaster.qa.requiredPageTypes must be an array',
            '- correctedMaster.qa.requiredLocales must be an array',
            '- correctedMaster.qa.rules must be an array',
            '- correctedMaster.qa.placeholderPolicy.allowed must be ["{child_name}", "{child_pronoun_subject}", "{child_possessive_det}"]',
            '- correctedMaster.qa.scorecard: editorialScore, imageabilityScore, heroConsistencyScore, localeCompletenessScore (each: {"value":0-100,"rationale":"..."})',
            '- Do NOT trigger image generation, production publishing, or any external sync',
            '- If the full correctedMaster exceeds your output capacity, focus on fixing ONLY the underperforming dimensions and leave the rest identical to the input.',
            '- Truncated or brace-imbalanced responses will be REJECTED. Count your braces before outputting.',

            '',
            '=== INPUT DATA ===',
            '',
            'Original brief JSON:',
            $this->encodeJson($brief),
            '',
            'Raw master JSON to review and correct:',
            $this->encodeJson($rawMaster),
        ]);

        return [
            'prompt' => $prompt,
            'input' => [
                'prompt' => $prompt,
                'max_tokens' => 96000,
                'temperature' => 0.1,
            ],
            'debug' => [
                'briefSlug' => trim((string) ($brief['slug'] ?? '')),
                'rawMasterSlug' => trim((string) (($rawMaster['metadata']['slug'] ?? ''))),
                'localeKeys' => array_values(array_filter(array_keys(is_array($rawMaster['locales'] ?? null) ? $rawMaster['locales'] : []), 'is_string')),
            ],
        ];
    }

    private function encodeJson(mixed $value): string
    {
        $encoded = json_encode($value, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        if (false === $encoded) {
            throw new \RuntimeException('Unable to encode QA prompt payload to JSON.');
        }

        return $encoded;
    }
}
